### ISSUE TITLE
Simplify fractions (1/2/3/4/5/6/7/8/9)

### ISSUE THREAD

**Issue by Redseb** [Redseb/Problemon#12]
Currently when integrating the game calculates strange fraction forms such as 1/2/3x^3 - which while technically correct looks a bit strange, the math program should automatically simplify the fractions into something like 1/6x^3

Eg.
Integrate x --> 1/2x^2
Integrate 1/2x^2 --> 1/2/3x^3

**Comment by maxdubakov** [comment]
I know bout this problem, hopefully, i will fix it by tomorrow
