### ISSUE TITLE
Calculate Crashes Program

### ISSUE THREAD

**Issue by Redseb** [Redseb/Problemon#15]
Following the math fraction update calculate crashes the game.

Eg. 
- Calculate 1/3x^3-12x
- x = 1
- Type in -11.66 (or anything doesn't matter it crashes)
- Crash with message `TypeError: null is not an object (evaluating 'numAndDenom2[1]')`

Also sometimes crashes on calculate with error `TypeError: Cannot read property '1' of null`

I am leaving this commit unpushed to Expo and to the web until we resolve it.

**Comment by Redseb** [comment]
![image](https://user-images.githubusercontent.com/10607934/75609405-89eb8100-5b08-11ea-8488-c935fac4daea.png)

Error continues, maybe its only negative numbers? Not sure

**Comment by Redseb** [comment]
Another crash - again with a negative number so I do think the problem is with negatives. Or at least for the `TypeError: Cannot read property '1' of null` error

**Comment by maxdubakov** [comment]
With negatives it is ok as well

**Comment by Redseb** [comment]
I just checked a different negative and it worked so idk what it is
