### ISSUE TITLE
NaN Calculate Bug

### ISSUE THREAD

**Issue by Redseb** [Redseb/Problemon#16]
![image](https://user-images.githubusercontent.com/10607934/75609147-7b9c6580-5b06-11ea-9ba0-7574608cb2d7.png)

Calculate x = 4. Results in NaN

**Comment by Redseb** [comment]
![image](https://user-images.githubusercontent.com/10607934/75609233-16953f80-5b07-11ea-85c1-b2b383cfd1b0.png)

Calculate x = 6, same issue

**Comment by Redseb** [comment]
![image](https://user-images.githubusercontent.com/10607934/75609384-54df2e80-5b08-11ea-90fe-6b6852df6a08.png)

Calculate x = 6, also NaN

**Comment by maxdubakov** [comment]
I have it working on my PC, maybe problem is on frontend side?
