### ISSUE TITLE
Another keyboard

### ISSUE THREAD

**Issue by maxdubakov** [Redseb/Problemon#2]
When a user taps to area of input a special keyboard will appear (only with numbers, signs and power sign)

**Comment by Redseb** [comment]
Implemented a built-in keyboard with only numbers, signs, and special buttons.

The only difference from the original issue is that the keyboard is always open, which I believe makes more sense

**Comment by Redseb** [comment]
oh yeah I also pushed this version to Expo and am building a new apk for the playstore
